pig:
  id: 1
  name: 佩奇
  age: 5
sheep:
  id: 1
  name: 蘇西
  age: 5
spring:
  data:
    redis:
      host: localhost
      port: 6379
person:
  name: 張三
  id: 18
  birthday: 2020/02/16 12:12:12
  like: true
  child:
    name: 李四
    age: 12
    birthday: 2024/02/16 12:12:12
    text: ["abc", "def"]
  dogs:
    - name: 小黑
      age: 1
    - name: 小白
      age: 2
  cats:
    c1:
      name: 小咪
      age: 3
    c2: {name: 小喵, age: 4}